### ISSUE TITLE
query remains watched in cache after unmounting the wrapped component

### ISSUE THREAD

**Issue by jay1337** [apollographql/react-apollo#1258]
After unmounting a component wrapped with a query, the query remains watched in `InMemoryCache`. It leads to a major performance issue since writing to the cache (and so broadcasting watches) takes more and more time after each component mounting/unmounting.

To reproduce this you can just mount and then unmount many times a component wrapped with any QraphQL query and look at `this.watches.length` in `InMemoryCache` object.

**Version**
- apollo-client@2.0.0-rc.3
- react-apollo@1.4.16

**Comment by jbaxleyiii** [comment]
@jay1337 can you also try the newest rc (`rc.4`?)

**Comment by jay1337** [comment]
@jbaxleyiii Issue still there with `rc.4`

**Comment by jbaxleyiii** [comment]
@jay1337 that is actually intentional! Currently the updateQueries and the refetchQueries methods only work if an observable is present for that query. React Apollo has a query recycler which keeps the observable around to make this work. We will be deprecating those methods after the 2.0 launch so this can all be removed in the 3.0 because using the plain update method doesn't require the observable. 

I'll see about making recycling opt in though!

**Comment by jay1337** [comment]
@jbaxleyiii I understand the recycling trick. But when a query is switched to `'standby'` `fetchPolicy`, then it must be removed from the "broadcast watches" of `InMemoryCache`. Keep in mind that a "broadcast watch" can be very time consuming if its a big query. And if you mount then unmount many components when a user is using an app it will make the app really unusable after some time.

**Comment by jay1337** [comment]
Hey !

**Comment by jay1337** [comment]
Hey !

**Comment by hwillson** [comment]
This should no longer be an issue with current versions of React Apollo. Thanks!
