### ISSUE TITLE
2.0.0 typescript error in Apollo Provider, missing method in interface

### ISSUE THREAD

**Issue by JozefBiros** [apollographql/react-apollo#1299]
Intended outcome:
Upgrading from 1.x release to the 2.x release.

Actual outcome:
`Types of property 'client' are incompatible.`
      `Type 'ApolloClient<NormalizedCache>' is not assignable to type 'ApolloClient<Cache>'.`
        `Type 'NormalizedCache' is not assignable to type 'Cache'.`
          `Property 'add' is missing in type 'NormalizedCache'.`

How to reproduce the issue:
Install react apollo in a typescript project and run tsc

Version
- apollo-client@<2.0.1>
- react-apollo@<2.0.0>

**Comment by corydeppen** [comment]
Rather than using the `Cache` type, which is defined in the TypeScript `lib.dom.d.ts` declaration file, for the [generic parameter to `ProviderProps`](https://github.com/apollographql/react-apollo/blob/apollo-client-2.0/src/ApolloProvider.tsx#L15) in the `ApolloProvider` class, it may be more appropriate to use `any` to let the type flow through when the client is created. It may also be less confusing if the generic type parameter was renamed to something like `TCache` in the [`ProviderProps` interface definition](https://github.com/apollographql/react-apollo/blob/apollo-client-2.0/src/ApolloProvider.tsx#L10)  so it's not confused with the `Cache` type.

I tested this change in the `ApolloProvider.d.ts` file and noticed the error went away and the client was properly typed as `NormalizedCache` when defining the cache as `InMemoryCache`.

**Comment by amborle** [comment]
@corydeppen thanks, this worked! Can you make a pull request?

**Comment by Jannis** [comment]
Who's in charge of deciding how this gets fixed? I'm also hitting this with
```
    "apollo-cache-inmemory": "^1.0.0",
    "apollo-client": "^2.0.1",
    "apollo-link-http": "^1.1.0",
    "apollo-link-state": "^0.0.4",
    "graphql": "^0.11.7",
    "graphql-tag": "^2.5.0",
    "react-apollo": "2.0.0",
```
