### ISSUE TITLE
Queries Failing After resetStore()

### ISSUE THREAD

**Issue by danstepanov** [apollographql/react-apollo#1322]
**Intended outcome:**

User signed out after `resetStore()` and queries refetched for components not requiring an authenticated user.

**Actual outcome:**

User seems to have been signed out but upon refetch of existing queries (that presumably do not require an authenticated users), `resetStore()` fails with the following error.
<img width="424" alt="screen shot 2017-11-04 at 11 31 29 pm" src="https://user-images.githubusercontent.com/5482800/32411752-8c228cf6-c1b9-11e7-8735-e7e6075d0679.png">

**How to reproduce the issue:**
Cannot provide code to reproduce due to IP nonsense. :(

**Version**
- apollo-client@<version number> (not using it)
- react-apollo@1.4.15

**Comment by Panoplos** [comment]
I had the same issue. I was calling this inside of a Redux resolver logic, however, before dispatching another event that actually set the authenticated parts to null. This worked in the previous version of apollo client, as it used Redux as the store, but failed on the new release due to a race condition (as resetStore triggers the chain of updates in the react component stack before the authentication data change is stored in Redux). Moving this call to post-resolver logic fixed it.

**Comment by hwillson** [comment]
The Apollo Client API now includes a [`clearStore`](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.clearStore) function that should help, that will clear the store without trying to re-run watched queries. Thanks!
