### ISSUE TITLE
renderToStringWithData runs twice

### ISSUE THREAD

**Issue by ravilution** [apollographql/react-apollo#1361]
Hi,
`renderToStringWithData` is trying to render the supplied React element twice. Please check the below code and output. I am using node v8.9.0

**package.json**
```javascript
{
  "name": "ssr-renders-twice",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-client-preset": "^1.0.3",
    "apollo-server-express": "^1.2.0",
    "express": "^4.16.2",
    "react": "^16.2.0",
    "react-apollo": "^2.0.1",
    "react-dom": "^16.2.0"
  }
}

```

**index.js**
```javascript
var React = require("React");
var express = require("express");
var renderToStringWithData = require("react-apollo").renderToStringWithData;

const app = express();

function App() {
  console.log("inside App");
  return React.createElement("div", null, "app");
}

app.get("/", async (req, res) => {
  console.log("req.url", req.url);
  const reactHTML = await renderToStringWithData(
    React.createElement(App, null)
  );
  res.send(`<!doctype html><html><body>${reactHTML}</body></html>`);
});

app.listen(3000, () => {
  console.log("started at ", new Date().toLocaleString());
});
```
**output**
```sh
started at  2017-11-28 14:07:57
req.url /
inside App
inside App
```

**Comment by foxCanFly** [comment]
The same with `await getDataFromTree(bodyComponent);`

**Comment by ravilution** [comment]
Because of this, when I do SSR, I always get html between `if(loading){}` and not on `else if (data){}`

**Comment by johnunclesam** [comment]
+1

**Comment by foxCanFly** [comment]
Maybe it could be useful. For me this was happening because of not very obvious usage of Provider which is not only pass functionality or variables inside context but wrap component in another "util" component. And that's fine. So we have to use this `ApolloProvider` or something like this. Before I just set context manually and had the same problem because I didn't have this additional functionality from `ApolloProvide`.

**Comment by johnunclesam** [comment]
@foxCanFly can you post an example? Maybe on https://codesandbox.io/?

**Comment by mkochendorfer** [comment]
I have run into the same thing causing various weird unexpected behaviors in my app due to the duel render/constructors.  This occurs because getDataFromTree and ReactDOM.renderToString both construct independent instances of the application.

This can lead to really baffling behaviors if you try to build your ApolloClient instance inside of a React component instead of outside of the React app in your SSR code.  Specifically it causes the SSR to fail because it builds up all of the data requests in getDataFromTree on the first render/constructor, but then it throws that app away and builds a new one in ReactDOM.renderToString with a fresh ApolloClient built in the constructors of the components again but now with none of the data from the initial tree traversal.

**Comment by hwillson** [comment]
This should no longer be an issue with current day versions of `react-apollo`. Thanks!

**Comment by mkochendorfer** [comment]
@hwillson Can you elaborate on how this was fixed/improved?

**Comment by hwillson** [comment]
@mkochendorfer Sure thing; `getDataFromTree` (which `renderToStringWithData` is using) was completely re-written in [`react-apollo` 2.3.0](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#improvements-13). This new implementation has addressed many of the outstanding `getDataFromTree` / `renderToStringWithData` issues. Let us know if you're still running into any problems.

**Comment by mkochendorfer** [comment]
@hwillson Thanks for the extra context.
