### ISSUE TITLE
Unable to bundle using rollup

### ISSUE THREAD

**Issue by vladshcherbin** [apollographql/react-apollo#1590]
**Intended outcome:**

I'm trying to bundle an app using rollup. Bundling basic react app works, but gives errors when react-apollo is added.

**Actual outcome:**

Rollup gives errors. The problem is that without `browser` [flag](https://github.com/VladShcherbin/rollup-react-app/blob/master/rollup.config.js#L18) it takes `stream` and with flag it takes `umd` version. I've seen this [PR](https://github.com/apollographql/react-apollo/pull/1576) and with latest beta it gives this errors. Not sure how to solve this normally.

Rollup errors:

- when not using `browser` flag in [config](https://github.com/VladShcherbin/rollup-react-app/blob/master/rollup.config.js#L18)

![screen shot 2018-01-29 at 08 13 49](https://user-images.githubusercontent.com/6711845/35494699-6eb84ba4-04cd-11e8-84ac-15a294730f06.png)

- when using browser flag in config

![screen shot 2018-01-29 at 08 14 09](https://user-images.githubusercontent.com/6711845/35494706-7b34bd0e-04cd-11e8-8b9f-680282a918ad.png)

**How to reproduce the issue:**

Here is a simple reproduction repo - https://github.com/VladShcherbin/rollup-react-app

Use two commands to see errors, use [this flag](https://github.com/VladShcherbin/rollup-react-app/blob/master/rollup.config.js#L18) to toggle `browser` target:

```
yarn
yarn build:rollup
```

**Version**

[Package versions](https://github.com/VladShcherbin/rollup-react-app/blob/master/package.json#L9-L16)

**Comment by jaydenseric** [comment]
It's not working for me with Webpack via Next.js either.

**Comment by VladShcherbin** [comment]
@jaydenseric I've tested 2.1.0-beta.0 and it's working for me with webpack, which can bundle almost any shit you throw in it.

I also tested https://github.com/apollographql/react-apollo/issues/1591 and it also works for me.

**Comment by VladShcherbin** [comment]
@jaydenseric I've added webpack config and build to the [repo](https://github.com/VladShcherbin/rollup-react-app) if it can somehow help.

**Comment by bthallion** [comment]
I'm seeing the same errors using rollup in react-apollo 2.0.4

**Comment by sholladay** [comment]
So the proper fix would involve `react-apollo` providing an actual ES module build, which it's certainly capable of doing since it's bundled with Rollup. That would make it much easier for modern bundlers to import the library.

That said, here are two workarounds that are available.

1. Use the default export instead

    Take code like this...
    ```js
    import { ApolloProvider } from 'react-apollo';
    console.log(ApolloProvider);
    ```
    ... and replace it with ...
    ```js
    import apollo from 'react-apollo';
    console.log(apollo.ApolloProvider);
    ```
    Or if you don't like the namespace...
    ```js
    import apollo from 'react-apollo';
    const { ApolloProvider } = apollo;
    console.log(ApolloProvider);
    ```

2. Use the commonjs plugin's [custom named exports](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports) feature

    ```js
    commonjs({
        include : [
            'node_modules/**'
        ],
        exclude : [
            'node_modules/process-es6/**'
        ],
        namedExports : {
            'node_modules/react-apollo/react-apollo.browser.umd.js' : [
                'ApolloProvider'
            ],
            'node_modules/react/index.js'                   : [
                'Children',
                'Component',
                'createElement'
            ]
        }
    }),
    ```

The first approach simply imports the UMD `exports` object as it is. It's a little less future proof since `react-apollo` will undoubtedly provide true named exports in the future, at which point it probably wouldn't have these classes hanging off the default export. The latter approach allows you to treat `react-apollo` as if it had named exports, but you have to specify them by hand since the UMD build is not statically analyzable and Rollup does not want to make assumptions about the `exports` object that it cannot confidently infer.

**Comment by dai-shi** [comment]
As this is still open, here is my workaround.
https://github.com/ds300/patch-package

[apollo-cache-inmemory+1.3.5_patch.txt](https://github.com/apollographql/react-apollo/files/2476382/apollo-cache-inmemory%2B1.3.5_patch.txt)
[react-apollo+2.2.4_patch.txt](https://github.com/apollographql/react-apollo/files/2476383/react-apollo%2B2.2.4_patch.txt)

**Comment by hwillson** [comment]
Our bundling strategy has been revamped in recent versions of `react-apollo`. If this is still a problem using `react-apollo` 2.5.6, let us know. Thanks!

**Comment by vladshcherbin** [comment]
Seems to be fixed now, thanks 🎉
