### ISSUE TITLE
`fetchPolicy` of `cache-only` won't throw an error when data isn't in the cache

### ISSUE THREAD

**Issue by migueloller** [apollographql/react-apollo#1751]
**Intended outcome:**

I am expecting an error when setting `fetchPolicy` to `cache-only` and querying data that is not in the cache. This is documented [here](https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-fetchPolicy).

**Actual outcome:**

Instead of throwing an error, `data` is simply an empty object.

**How to reproduce the issue:**

https://codesandbox.io/s/7361K9q6w

**Version**

* apollo-client@2.2.5
* react-apollo@2.1.0-beta.3

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
