### ISSUE TITLE
Mutation/Query on no network connectivity returns undefined data 

### ISSUE THREAD

**Issue by BalajiJagadeesan** [apollographql/react-apollo#1944]
I have been testing my application (react native mobile app) on various scenarios, one such case is, how query/mutation acts if there is no network.  

Behavior:
I enabled cache(Android AsyncStorage) in Apollo client. So, when there is no network, query or mutation is taken from the cache (if that said query/mutation is already invoked and cached). If it is not present in the cache, it returns an error like "_ref.data  undefined and crashes the application.

I feel like the request should be queued when there is no network and not found in the cache

When the server is down and the request is invoked. It will show loading and gracefully end in some graphqlError.But this is not the case when there is no network.

I use the 2.0's new Mutation and Query component to fetch data. 

Please look at this for understanding the issue
![video behavior](https://user-images.githubusercontent.com/11597497/39207932-275e2cf2-47b6-11e8-9210-3b82a14cc6b1.gif)

Here, I request some data when it is online . The data is cached and is available when the device is offline.Tested, works as expected.
When I request new data in offline mode (which is not cached),the application crashes.

Is this the correct behavior?? 

Package version:
"graphql": "^0.13.2",
"graphql-tag": "^2.8.0",
"react-native": "0.53.3",
"react": "16.3.0",
"react-apollo": "^2.1.3",
"apollo-cache-inmemory": "^1.1.12",
"apollo-cache-persist": "^0.1.1",
"apollo-client": "2.2.7",
"apollo-fetch": "^0.7.0",
"apollo-link-context": "^1.0.7",
"apollo-link-http": "^1.5.3",

**Comment by xialvjun** [comment]
me too. I expect
```jsx
<Query>
  {({ data, loading, error }) => {
    // if it's offline, error shouldn't be undefined
  }}
</Query>
```

**Comment by acro5piano** [comment]
Me too.

In my case, I would like to `refetch` if network status become online, but `data` become `undefined`.

**Comment by ext-vt-vfa-trungbb** [comment]
Me too. Have any one already resolved it ?

**Comment by acro5piano** [comment]
After various research, my conclusion is to stop to use Apollo.

In my case, I use react-apollo with React Native and found react-apollo is not suitable for it because screens don't unmount nor re-mount in React Navigation's stack navigation. This causes a lot of unexpected errors from "hidden" screens which could not be seen behind current stack screen.

You could handle `data` become `undefined` with a lot of care If you use React on web, but I can't recommend to use react-apollo in RN.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
