### ISSUE TITLE
Possible cache isolation when using react portal

### ISSUE THREAD

**Issue by newsiberian** [apollographql/react-apollo#1960]
**Intended outcome:**

Hello. I'm not sure is this a bug or not.

I'm expected to have end-to-end caching while using `react portal` in any way.

**Actual outcome:**

I noticed that component's apollo state (cache) created with `react portal` may be isolated from app apollo state. In my case I'm builded oauth authentication over some of the social networks and as you know it has a callback stage. So I'm using `react portal` to verify access and catch oauth callback. All oauth interaction goes within new tab window which is opened with `react portal`. After it is finished and I receive account credentials from an api. I save them into cache, but after this tab closing, main window doesn't receive this changes.

**How to reproduce the issue:**

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.3

**Comment by rosskevin** [comment]
If you are using a different `client` within a portal, it could cause this, otherwise if you setup a single client/cache for the app you will not.  A client with an InMemoryCache (if that is what you use) is per browser window, which is not equal to a react portal (which is in the same window)

Closing - housekeeping
