### ISSUE TITLE
Pass `extensions` to the client

### ISSUE THREAD

**Issue by yorch** [apollographql/react-apollo#2059]
Currently, our GraphQL server uses `extensions` property in the response payload to send extra meta data (like metrics and other stuff). I would need to consume this information on either the `grapqhl` HOC or the `Query` Component, but doesn't seem like it's exposed in any way.

I see the information in a custom link in our Apollo Client, but can't find a way to pass that info to the client (ie, I tried using `context`, but it seems like it's only one way communication, from HOC / Query component to Apollo Link).

Am I missing something?

**Intended outcome:**

Get `extensions` along side `data`, `errors`, `loading` in the `graphql` HOC and / or Query component.

**Version**

* apollo-client@2.3.1
* react-apollo@2.1.4

**Comment by djyde** [comment]
need it, too

**Comment by nikordaris** [comment]
I might look at this next week but if you can see the extensions data in the custom link then you probably can do something like this:

```js
new ApolloLink((operation, forward) => new Observer((observer) => {
  forward(operation).subscribe({
    next: (result) => {
      // Some how get extensions passed from server
      result.extensions = extensions
      observer.next(result);
    },
    error: (error) => {...}
    complete: observer.complete.bind(observer),
  });
  return () => {
    if (sub) sub.unsubscribe();
  }
}));
```
then in theory you should have access to the `extensions` data along side `data`, `error`, and `loading`. If you try it out before I do let me know if it works!

**Comment by rosskevin** [comment]
Please feel free to PR a proposed solution that works for you and we can review it. Looks like an addition so it could be integrated without breaking changes.

**Comment by rosskevin** [comment]
Minimally you will need to touch apollo-link and react-apollo, but perhaps apollo-client as well. @hwillson do you have some pointers here?  This likely impacts several projects as a new feature and should have some design oversight.

**Comment by bsara** [comment]
I started looking through the code to see how difficult this would be. If I'm understanding things correctly, this a big update. The issue is not in the link. The link already forwards on `extensions` when it is received. The update seems to need to be in apollo-cache. The cache stores `data` from the response and ignores `extensions` altogether. Then, whenever `data` is retrieved to be passed to the child function of a `Query` component, it is retrieved from the cache. This means that `extensions` would need to be stored alongside or with `data` in the cache somehow. I'm brand new to the codebase, so I don't know what the complexities would be to add such a thing, but from my initial experimentation, it's not a small task, given the fact that the cache is itself a graph that can be queried against. I hope that I'm wrong about the difficulty of it though.

**Comment by bsara** [comment]
@sgrove I actually found your blog article while searching and looked through your code for a bit but couldn't find the solution that you had described in the article, so thank you for the link.

I've ended up doing a similar thing. We have redux in our app as well, so I create a custom link that just updates the redux store with the extensions for the query performed.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Pass%20%60extensions%60%20to%20the%20client&body=Migrated%20from:%20apollographql/react-apollo%232059) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
