### ISSUE TITLE
Query component and Error handling

### ISSUE THREAD

**Issue by yordis** [apollographql/react-apollo#2087]
Recently I am trying to contribute to `vue-apollo` and I came across to some issue that I couldn't understand.

I was trying to mimic the implementation of `react-apollo` since `vue-apollo` do not use `ApolloError` in this case https://github.com/Akryum/vue-apollo/blob/b52e9e07bdf982147705e4e289b76fe4ef8111b0/src/components/ApolloQuery.js#L121

So I went ahead and changed and I tried to test it with returning an graphql error result.

I expected these block of codes to run

https://github.com/Akryum/vue-apollo/blob/b52e9e07bdf982147705e4e289b76fe4ef8111b0/src/components/ApolloQuery.js#L120-L123

https://github.com/apollographql/react-apollo/blob/5b2e340edcf2b5a3e4e5ef6f86b486f8ce5e22a6/src/Query.tsx#L368-L370

but in neither project that I setup worked.

Which now I am asking myself if we need those block of code at all at this point.

Even when in fact there is a grahpql response with an `errors` key on it, still the `result.errors` is always `undefined` but `result.error` is the already created `ApolloError` with the list of errors inside.

@jbaxleyiii I would like to confirm this, I checked and you are the person who introduce the block of code, please help me with this.

**Version**

* apollo-boost@0.1.7
* react-apollo@2.1.4

**Comment by rosskevin** [comment]
Closing - housekeeping

**Comment by yordis** [comment]
@rosskevin does housekeeping means fixed issue or just closed it? I just see that you are closing issues but that doesn't mean they are fixed.

**Comment by rosskevin** [comment]
@yordis Please state the expected outcome and the actual outcome if you have a problem, this looks like a question for stackoverflow.  This appears to be a question which can be resolved by looking at the code or the defined typescript types.

**Comment by rosskevin** [comment]
Hi @yordis I read your comment but it was not clear to me what you are after.  The new issue template structures these issues a bit better so that it is easier to triage.  After re-reading your message several times, I think I understand.  Please bear with me as I am a volunteer trying to triage hundreds of issues today to help out this project on my own time.

Based on the types defined:

```ts
export interface QueryResult<TData = any, TVariables = OperationVariables>
  extends ObservableQueryFields<TData, TVariables> {
  client: ApolloClient<any>;
  data: TData | undefined;
  error?: ApolloError;
  loading: boolean;
  networkStatus: NetworkStatus;
}
```

and this block of code:

```ts
      // Until a set naming convention for networkError and graphQLErrors is
      // decided upon, we map errors (graphQLErrors) to the error props.
      if (errors && errors.length > 0) {
        error = new ApolloError({ graphQLErrors: errors });
      }
```
you can see that you will receive a single error or undefined.

We _do_ still need this block of code to meet our public API.  If we want to introduce a change to that it would have to be roadmapped for a major version change.  You are free to file a PR for a change to this behavior - just list as `breaking change` and list as 3.x.  I believe the core maintainers are going to begin work on this soon.
