### ISSUE TITLE
Client from options is not used after a skip

### ISSUE THREAD

**Issue by sarahLardeau** [apollographql/react-apollo#2331]
**Intended outcome:**

I was upgrading react-apollo when I discovered this behavior. It works fine with react-apollo@2.0.4
First of all, we are still using old HOC way.

What happened ?
I have a component which needs a special client. No problem, I use client option ! But I need to skip the query in some circumstances, so I use skip parameter !

Ok so my component looks like this 
```
export default graphql(Query, {
  options: {
    client: anotherClient
  },
  skip: props => props.skip
})(Component);
```

**Actual outcome:**

The issue is if the query is skip and then unskip after a while, the client set in options is not used, the query uses client from ApolloProvider instead.

**How to reproduce the issue:**

https://codesandbox.io/embed/7jvyv59060

**Version**

* apollo-client@2.4.1
* react-apollo@2.1.11

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
