### ISSUE TITLE
Mutation component overrides apollo-client's defaultOptions.mutate

### ISSUE THREAD

**Issue by isilkor** [apollographql/react-apollo#2360]
**Intended outcome:**
The Mutation component should honor settings in the base client's `defaultOptions.mutate`.

**Actual outcome:**
The component passes an options object with several properties to the client, which are left undefined if the user does not set the prop on the component. Since apollo-client merges the options with a plain `Object.assign`, these existing but undefined options override defaultOptions of the same name.

**How to reproduce the issue:**
https://codesandbox.io/s/qvknmwlr04
Click the button. Observe that the expected alert is not shown. The alert is shown if the Mutation component is passed an explicit `update` prop or if use of the Mutation component is replaced by a direct call to apollo-client.

**Version**
* apollo-client@2.3.5
* react-apollo@2.1.6

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
