### ISSUE TITLE
UI not updated on network error

### ISSUE THREAD

**Issue by miguelocarvajal** [apollographql/react-apollo#2613]
**Intended outcome:**

UI is not updated when the cache is directly updated (writeQuery) and there is a network error in a Query.

**Actual outcome:**

This works correctly if the fetchPolicy is cache-only, but any other policy that accesses the network stops working when there is a network error.

**How to reproduce the issue:**

https://codesandbox.io/s/zqwz73qwm

**Version**

- apollo-client@2.4.7
- react-apollo@2.3.1

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
