### ISSUE TITLE
onCompleted not called if cache updater function invoked

### ISSUE THREAD

**Issue by leanne2** [apollographql/react-apollo#2615]
**Intended outcome:**
onCompleted callback called

**Actual outcome:**
onCompleted callback not called until i commented out the mutation update function contents e.g when i stopped updating the cache. My guess is its related to this issue: https://github.com/apollographql/react-apollo/issues/2531 because the component making the mutation is nested in another container whose values are updated by the updater function (and therefore causing a re-render of the component with the onCompleted callback) 

**Version**

- apollo-client@2.4.2
- react-apollo@2.2.3

**Comment by Rkuro** [comment]
I commented on issue #2531  [here](https://github.com/apollographql/react-apollo/issues/2531#issuecomment-447593394) Hope it helps.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
