### ISSUE TITLE
Not related component rerendering on other component polling

### ISSUE THREAD

**Issue by dimkabuki** [apollographql/react-apollo#2723]
I have a couple of components which are using Query component. Some of them are doing polling.
And the issue that when errors appear, it start to re-render this component with other components.
Here is a simple example
https://codesandbox.io/s/q94819q36q
(open console to see how it's looks)
For the pure component it is not an issue, but if I have a logic with this error status, for example showing an error message, that could be a problem

- apollo-client@2.4.8
- react-apollo@2.3.3

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
