### ISSUE TITLE
flickering data

### ISSUE THREAD

**Issue by amlcodes** [apollographql/react-apollo#2733]
when using a query  component, data is first {} yet not returning true when evaluating (data == {}). if you dont return a value when data is empty, it spits an error. I'm not sure what to do since my evaluations are false yet my data is clearly an empty object

**Comment by JoviDeCroock** [comment]
The first thing to check when querying data is if you are still loading or not, when logging it there's a chanche you are logging an updated ref. so the best practice when logging rapidly changing variables is to use `console.log({ ...data })`. Lastly you should check your network tab to see if data comes in or not.

Good luck on the issue, always happy to help further if the issue is a bit more clear.

**Comment by rosskevin** [comment]
Please ask questions on StackOverflow or slack.
