### ISSUE TITLE
Infinite loop during a render of the App. Caused by changing query variable

### ISSUE THREAD

**Issue by koprivajakub** [apollographql/react-apollo#2744]
**Intended outcome:**

I have a Query with variable timestamp where I should send a current client timestamp in milliseconds. This cause the render function of the App infinitely looping during SSR.

If I comment out the `getDataFromTree` from the apollo HOC then it starts working, obviously. The other way how to bypass this problem is to send a fixed value that does not change over time, for example a constant string or number. I think that I am doing something really wrong because this should not happen. So if you have any questions, but mainly suggestions please let me know.

Here is an example code that can reproduce the problem.
https://github.com/koprivajakub/nextjs-with-apollo-infinite-render-loop

**Actual outcome:**
Server side rendering is looping in the `getDataFromTree`

**How to reproduce the issue:**

Here is an example code based on the next's framework that can reproduce the problem.
https://github.com/koprivajakub/nextjs-with-apollo-infinite-render-loop

**Version**

- apollo-client@2.4.11
- react-apollo@2.3.3
- nextjs@7.0.2

**Comment by danilobuerger** [comment]
That is expected since you are creating a new query on each render thus forcing it to be queried again. 

Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
