### ISSUE TITLE
this.context.renderPromises.getSSRObservable is not a function

### ISSUE THREAD

**Issue by HeadFox** [apollographql/react-apollo#2779]
**Error:**
```GraphQL error occurred [getDataFromTree] TypeError: this.context.renderPromises.getSSRObservable is not a function```

**How to reproduce the issue:**
Install version 2.4.1 of react-apollo, the error was not present on 2.4.0

**Version**

- apollo-boost@0.1.27
- react-apollo@2.4.1
- next@7.0.2

**Comment by dep** [comment]
I have a similar error after updating to apollo 2.4.1.

**Comment by benjamn** [comment]
The call to `getSSRObservable` was added in the same PR that implemented the method, along with tests: https://github.com/apollographql/react-apollo/pull/2753

To move forward here I think we'll need a reproduction that shows how this error could happen, since I have to admit I don't have any guesses.

**Comment by benjamn** [comment]
We haven't heard back about a reproduction in a while, and a new minor version has been released in the meantime. Closing now, but please feel free to reopen if you have new evidence this is still a problem!
