### ISSUE TITLE
refetchQueries breaks unrelated queries' cache

### ISSUE THREAD

**Issue by Elijen** [apollographql/react-apollo#2838]
**Intended outcome:**

After a mutation is done, queries listed in `refetchQueries` should be updated without affecting other queries.

**Actual outcome:**

Component created by `graphql` HOC is passed in props that are obviously not correct. This component does not even use the query mentioned in `refetchQueries`. Removing the `refetchQueries` option fixes the problem.

```
{
"data": undefined,
"error": undefined,
"loading": false,
"networkStatus": 7,
}
```

**How to reproduce the issue:**

I am not exactly sure how to reproduce, does not happen on each mutation. Will update the issue once I figure it out.

**Version**

- apollo-client@2.4.8
- react-apollo@2.4.1

**Comment by Elijen** [comment]
Seems to be related or caused by https://github.com/apollographql/react-apollo/issues/2838

**Comment by aemc** [comment]
Had a related issue where a component containing a <Query/> will fetch data just fine from cache. But a remount will cause no data to be fetched from cache IF its an object. I've fixed(?) the issue by removing persistent caching for now.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
