### ISSUE TITLE
Refetch hangs instead of failing when network is down

### ISSUE THREAD

**Issue by lukewlms** [apollographql/react-apollo#2951]
**Intended outcome:**

Refetching when network is down should immediately fail.  onError should be immediately called, if it is present in a link.

**Actual outcome:**

Refetching with new variables sets networkStatus to setVariables and then hangs.  Triggering multiple refetches finally causes the request to fail and onError to be called.

If network is down when the _initial_ query runs (not the refetch), onError will (correctly) immediately be called.

**How to reproduce the issue:**

Try to refetch when network is unavailable.

(I tried to create a minimal repro but am thwarted by CORS - I can't connect to the example server.  However this consistently repros in our code base.  I also can't use the example product since it doesn't work with the network.)

**Version**

- apollo-client@2.5.1 (latest)
- react-apollo@2.5.4 (latest)

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
