### ISSUE TITLE
config.name is not type safe

### ISSUE THREAD

**Issue by slikts** [apollographql/react-apollo#2959]
The way `config.name` is used with `graphql()` to avoid conflicts affects typing in two ways:
 - the `mutate` and `data` props become nullable, since their name can be changed with `config.name`, so the user needs to either use a type guard or assertion;
 - the prop set with `config.name` is not type safe, because it's 'stringly' typed.

I've ran into this issue when adding the result states to the mutation HOC for #2952.

Other approaches, such as react-adopt for components, avoid relying on strings and so are safely typed, but it's not immediately clear how to implement a similar solution for HOCs.

**Comment by slikts** [comment]
Seems to be the same issue as #809, so maybe it's a regression.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
