### ISSUE TITLE
`cache-only` query stuck in loading state after `client.resetStore()`

### ISSUE THREAD

**Issue by gbiryukov** [apollographql/react-apollo#2978]
**Intended outcome:**

Query should pass `loading: false` and actual state from cache after `client.resetStore()` call for `cache-only` queries

**Actual outcome:**

Query stuck in loading state forever. 
`notifyOnNetworkStatusChange={true}` hack does not solve issue.

**How to reproduce the issue:**

Repro for network data: https://codesandbox.io/s/48kj969v07
Repro for local state: https://codesandbox.io/s/n739m44k50

might be related: #807

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.4

**Comment by ElForastero** [comment]
It can be related to https://github.com/apollographql/react-apollo/issues/2899

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
