### ISSUE TITLE
Query with fetchPolicy "no-cache", SSR of false performing server side rendering

### ISSUE THREAD

**Issue by bpaske** [apollographql/react-apollo#3000]
A query made with SSR={false} and fetchPolicy="no-cache"appears to be performing server side rendering. The same query with fetchPolicy="network-only" seems to work correctly.

**Intended outcome:**
Query not rendered on the server

**Actual outcome:**
Query is rendered server side.

**How to reproduce the issue:**
1. Create query with these (or similar) properties: 
```
      <Query
        query={TREE_LAYOUT}
        ssr={false}
        errorPolicy="all"
        variables={{
          personId,
          transcriptId,
          transcriptType,
          consumingSiteId,
        }}
        fetchPolicy="no-cache"
      >
```
2. Observe query being made server side and render prop function being called in debugger attached to the server side code.

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.5

This appears to be a regression as it was not occurring in react-apollo@2.3.1. and apollo-client@2.3.5

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
