### ISSUE TITLE
Query component doesn't properly unsubscribe previous querySubscription

### ISSUE THREAD

**Issue by magne4000** [apollographql/react-apollo#3028]
**Intended outcome:**
`Query` component should always unsubscribe previous subscription before starting a new one (or am I missing something?).

**Actual outcome:**
[Looking at `componentWillReceiveProps`](https://github.com/apollographql/react-apollo/blob/v2.5.5/src/Query.tsx#L213
), I see that `startQuerySubscription` is ultimately called, but `resubscribeToQuery` seems more appropriate, as it will unsubscribe any previous `queryObservable`.

Without it, libs that return Observable that can actually send multiple results like [reactive-graphql](https://github.com/mesosphere/reactive-graphql) (i.e. Observable is not closed from the inside after first data sent), are never cleaned-up properly.

**Version**
- apollo-client@2.6.0-beta.8
- react-apollo@2.5.5

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
