### ISSUE TITLE
How to use ApolloConsumer render prop with TypeScript?

### ISSUE THREAD

**Issue by maecapozzi** [apollographql/react-apollo#3055]
I'm looking for help using the `<ApolloConsumer />` render prop with TypeScript, without resorting to `any`. 

**Intended outcome:**
I wrote a function like this: 

```tsx
const writeProductsToCache = (products: Array<Product>) => (
  <ApolloConsumer>
    {(client) => {
      return client.writeQuery({
        query: GET_PRODUCTS,
        data: {
          products,
        },
      });
    }}
  </ApolloConsumer>
);
```

I expect this not to fail, and if it does, I expect to be able to see an example of how to type `client`.

**Actual outcome:**

I see a TypeScript error like this: 

```
error TS2322: Type '(client: ApolloClient<any>) => void' is not assignable to type '((client: ApolloClient<any>) => ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>) | ... 6 more ... | (((client: ApolloClient<...>) => ReactElement<...>) & ReactPortal)'.
  Type '(client: ApolloClient<any>) => void' is not assignable to type '(client: ApolloClient<any>) => ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>'.
    Type 'void' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>'.

 20     {client => {
        ~~~~~~~~~~~~
 21       return client.writeQuery({
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 26       });
    ~~~~~~~~~
 27     }}
    ~~~~~~

  node_modules/react-apollo/ApolloConsumer.d.ts:4:5
    4     children: (client: ApolloClient<any>) => React.ReactElement<any> | null;
          ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & ApolloConsumerProps & { children?: ReactNode; }'


Found 1 error.

error Command failed with exit code 1.
```

When I set `client` to `any`, the error goes away. 

```tsx
const writeProductsToCache = (products: Array<Product>) => (
  <ApolloConsumer>
    {(client: any) => {
      return client.writeQuery({
        query: GET_PRODUCTS,
        data: {
          products,
        },
      });
    }}
  </ApolloConsumer>
);
```

**How to reproduce the issue:**

**Version**

- apollo-client@^2.5.1
- react-apollo@^2.5.5

**Comment by jasonpaulos** [comment]
Hi @maecapozzi! To clarify, [ApolloConsumer](https://www.apollographql.com/docs/react/api/react-apollo/#apolloconsumer) is a usage of [React's Context API](https://reactjs.org/docs/context.html), which allows child React components to easily access resources made available by a provider, which in this case is [ApolloProvider](https://www.apollographql.com/docs/react/api/react-apollo/#apolloprovider). This means that the function given to ApolloConsumer **must** return a React component, as this is a requirement of the Context API. Since your function returns the output of [client.writeQuery](https://github.com/apollographql/apollo-client/blob/3bfa05a740830501510da15f959863dcd21f187b/packages/apollo-client/src/ApolloClient.ts#L403), which is void, TypeScript is correctly catching this error. When you add the `any` annotation to client, I believe you're essentially telling TypeScript to skip that entire section of code, so it doesn't report the error with the return type.

It looks like you're trying to use ApolloConsumer as a generic way to gain access to an instance of ApolloClient outside of a component's render function, which is not how it's intended to be used. I'm going to close this issue for now, but feel free to reply with any further questions.
