### ISSUE TITLE
 withApollo can be used in the lifecycles?

### ISSUE THREAD

**Issue by CarlFMateus** [apollographql/react-apollo#3082]
I have tried to use withApollo in the lifecycles sometimes it works but then these services fall, I would like to know if I can use two clients in a single component of lifecycle. Thanks

**Comment by CarlFMateus** [comment]
Please I need your help because it is generating several problems. I do not speak English very well

**Comment by kkotwal94** [comment]
I can't speak for the apollo team, but just to make sure, your asking if i'm connected to two different clients, how to use the withApollo HoC (Higher order component)?

I'm guessing the issue is that when you do withApollo(Component), the prop client is injected, but you're not sure which client it is specifically?

**Comment by hwillson** [comment]
Issues here are reserved for React Apollo bugs. You’ll have a much better chance of getting this answered in [Apollo’s Spectrum community](https://spectrum.chat/apollo) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/apollo). Thanks!
