### ISSUE TITLE
React state update error

### ISSUE THREAD

**Issue by hwillson** [apollographql/react-apollo#3128]
Moving this here from the [RA 3 PR](https://github.com/apollographql/react-apollo/pull/2892) thread: https://github.com/apollographql/react-apollo/pull/2892#pullrequestreview-242056659

cc @lucasecdb

----

oh, so sorry, I saw the `Query` component in my component stack and though the error was from it. Apparently it's happening because of this custom hook I've created:

```ts
const useLoading = (loading: boolean) => {
  const [mutate] = useMutation<LoadingMutation, LoadingMutationVariables>(
    LOADING_MUTATION
  )

  useEffect(() => {
    mutate({ variables: { loading } })
  }, [loading, mutate])
}
```

and this is the error I'm seeing:

![image](https://user-images.githubusercontent.com/10223856/58392746-d9e56680-8011-11e9-8a37-ea6d3bb4729d.png)

it's still weird that I'm getting this warning, because my component doesn't use any state, it only uses the `graphql` hoc and the hook I've pasted above.

----

So, according to the stack trace of the warning above, the error is coming from the `MutationData.updateResult` function

![image](https://user-images.githubusercontent.com/10223856/58394603-77dd2f00-801a-11e9-84dc-e883bb5e2385.png)

**Comment by hwillson** [comment]
@lucasecdb I haven't been able to re-create this issue unfortunately. If there's any chance you can provide a small runnable repro that shows this happening, that would be really helpful. Small side note - your `useEffect` call is listing `mutate` as one of it's dependencies:

```js
useEffect(() => {
    mutate({ variables: { loading } })
  }, [loading, mutate])
```

Since you're also including `loading` here that's okay (since the check against the previous `loading` value will prevent the effect from firing after every render). But I wouldn't recommend adding `mutate` as a dep for the effect, since React see's the `mutate` function as a new function on each render. Dependency equality checks that happen for effects are run through [React's `is` function](https://github.com/facebook/react/blob/e1c5e8720d5d47974c14c125dbaf3dc608a92936/packages/shared/objectIs.js), which just does a simple non-deep comparison. If `loading` wasn't also in your effect deps, your effect would be triggered after each render. Not that this is related to the issue you've seen, but just a heads up.

I'll close this for now, but happy to re-open if you can provide a small repro. Thanks!

**Comment by lucasecdb** [comment]
@hwillson I've been thinking of creating a small repro case, and I tried to to it on codesandbox but I couldn't get the graphql server running (I've forked an example that Peggy posted on twitter with hooks). I'll probably have to create a repo with the bug, and post it here later.

About the `mutate` in the deps list, I think it's desirable to have it in the array, since the eslint rule will always complain about the missing dependency, which would require either the dev to add it to the deps, or to add the `// eslint-disable-next-line react-hooks/exhaustive-deps` comment to disable the rule, which could cause a lot of other problems with syncronization of the other dependencies (forgetting to add one, or to remove another).

Probably, the best solution would be to always guarantee the identity of the `mutate` function returned from the hook, by using some combination of `useCallback` and `useRef`, but I can see why that may be complicated to do for now.
