### ISSUE TITLE
useSubscription hasn't cleaned up after unmount

### ISSUE THREAD

**Issue by Rusya44** [apollographql/react-apollo#3160]
**Intended outcome:**
subscription cleaned up after unmount

**Actual outcome:**
subscription hasn't cleaned up after unmount

**How to reproduce the issue:**
sorry for the lack of details, but it really is. I didn't found in repo any code that clean ups subscription after unmount

**Version:**
3.0.0-beta.2

**Comment by Rusya44** [comment]
Since I needed to solve it as soon as possible I ended up with this https://github.com/Rusya44/react-apollo/commit/73474cc23d57d866075032235088608d04a55f3e

**Comment by hwillson** [comment]
Thanks for reporting this @Rusya44. Can you give me an example of how this was impacting you? What issues were you encountering that were caused by `cleanup` not being called directly? We stoped calling it directly as it seemed unnecessary, due to the way we're use a ref to manage the internal data layer. Happy to fix this, but I'd love to get a test in place first to make sure we're addressing a specific problem.

**Comment by Rusya44** [comment]
The problem is that when the component that uses useSubscription unmounted — subscription remains active and I continue receiving notifications from the server even if I don't need them since component unmounted. And the most important thing is that when this component mounted again — subscription duplicated. Every time component is mounted — the number of subscriptions grows linearly, this is a bottleneck for the server.

**Comment by hwillson** [comment]
Great, thanks for the additional info @Rusya44! I'll find out why that didn't show up in testing, and get this addressed.
