### ISSUE TITLE
Query onCompleted functon not invoked when using 'cache-first' fetch policy 

### ISSUE THREAD

**Issue by TacticCoder** [apollographql/react-apollo#3165]
```
<Query
	variables={{ id: params.main }}
	query={getProduct}
	fetchPolicy="cache-and-network"
	onCompleted={(data) => {
	console.log('onCompleted trigger');
		title(data.wp_posts.post_title);
	}}
	>
	{({
		loading,
		error,
		data,
	}) => {
	if (loading) return 'Loading...';
	if (data.wp_posts.length === 0) return <Redirect to="/NotFound" />;
	if (error) return `Error! ${error.message}`;
	return <Single product={data.wp_posts} />;
	}}
</Query>
```

So i want to call 'someFunction()' when the data fetch is done. what's really happens, the desired function not called and console.log either.

react-apollo: 2.5.5

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
