### ISSUE TITLE
should useQuery return a tuple like useMutation?

### ISSUE THREAD

**Issue by sonacy** [apollographql/react-apollo#3182]
I am trying 3.0.0-beta here. 

useQuery will return the result when use in functional component.
i think useQuery should sth like useMutation, it will return a tuple, and i will use that query when i need it.
```js
   const [getNews] = useQuery(getNewsQuery)
   // so i can use getNews whenever i want
```
in that case i can use getNews in a effect hooks, maybe query sth new when dependency changed. 
Not really sure how to acheive this . hopes help.

**Comment by hwillson** [comment]
Thanks for this suggestion @sonacy. We're exploring a slightly different approach that is closer to https://github.com/apollographql/apollo-feature-requests/issues/119. Using the proposed `lazy` option will deliver the same functionality as your suggestion, and give us a bit more flexibility. For now let's tack the discussion in that FR. Thanks!

**Comment by stonebat** [comment]
I was thinking about the same feature after running into two issues with the current implementation of useQuery.

  const { data, loading, error } = **useQuery**(SOME_GQL, {
    variables: { input: { id: prop.id }
  })

When prop.id is empty, I don't want to run the query. But my functional component has to run since useQuery as a hook cannot be wrapped in a conditional statement. The order of hooks must be always same.

I have a refresh icon. Clicking on it should refetch the data. But there is no way to trigger the useQuery again. I wrote a dummy mutation and set its refetchQueries. Yes 2 full round trips.
