### ISSUE TITLE
Network fetch error apollo client postgraphile

### ISSUE THREAD

**Issue by CarlFMateus** [apollographql/react-apollo#3212]
Good morning I do not speak English well.
I have two projects that are being implemented with apollo client and postgraphile the problem is that there is an intermittence in the services. I am presented with this error:
Error: Network error: Failed to fetch
at new ApolloError (bundle.esm.js:76)
at bundle.esm.js:1556
at bundle.esm.js:1977
at Set.forEach ()
at bundle.esm.js:1975
at Map.forEach ()
at QueryManager.broadcastQueries (bundle.esm.js:1973)
at bundle.esm.js:1451

We don't have any related errors in the API. It seems to be when the user leaves the app open for a while; does Apollo have any bugs related to this when the user leaves an app open for a while?
Please help me with this problem I have two projects and I can not find a solution. Thanks

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
