### ISSUE TITLE
getDataFromTree is throwing an error, but the errors object is {}

### ISSUE THREAD

**Issue by ajhool** [apollographql/react-apollo#3265]
**Intended outcome:**
The main intended outcome is for getDataFromTree to succeed. However, when getDataFromTree fails, it should provide error information for further debugging. 

**Actual outcome:**
```
try {
  getDataFromTree(
    <App
        {...appProps}
        Component={Component}
        router={router}
        apolloShopifyClient={apollo}
       />
  );
} catch(err) {
  console.log('getDataFromTree error: ', JSON.stringify(err));
  // output is: getDataFromTree error: {}
}
```

**How to reproduce the issue:**
The nature of this bug makes it very hard for me to track down the error to create a reproduction.

**Version**
2.5.8

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
