### ISSUE TITLE
Query stuck in loading state after immediate error

### ISSUE THREAD

**Issue by jasonpaulos** [apollographql/react-apollo#3299]
**Intended outcome:**

When an error occurs, the Query component should render with the error property.

**Actual outcome:**

If a local link throws an error within less than 10ms (based on my trials) the Query component doesn't see the error and is stuck in the loading state forever.

This is really only an issue for testing, since over the network the delay is small enough to probably not matter, but a bug's a bug. 🐛

**How to reproduce the issue:**

https://codesandbox.io/s/react-apollo-immediate-error-j5ynd

**Version**

Using the latest beta version of `@apollo/react-components`, as shows in the codesandbox.

---

Found when investigating #3211 by @novemberborn.

**Comment by hwillson** [comment]
Thanks for reporting this @jasonpaulos! https://github.com/apollographql/react-apollo/pull/3313 should have fixed this (here's a new CS using the latest `@apollo/react-components` and it appears to be working properly - let me know if you notice otherwise: https://codesandbox.io/s/react-apollo-immediate-error-kbcwo). Thanks!
