### ISSUE TITLE
Query (in HOC) stuck in loading.

### ISSUE THREAD

**Issue by developdeez** [apollographql/react-apollo#3300]
I was using 2.5.6 and it was getting stuck.
I upgraded to 2.5.8 now it blinks several times before showing the page.

Im using a Query in my HOC to reject the user to the login if not logged in. Now it seems to make several repeated calls to the API for checking.

What gives?

HOC calls query like this: 
`<Query query={GET_CURRENT_USER} fetchPolicy="network-only" errorPolicy="none" >`

Body that wrapped by the HOC contains the react router switching between pages. The goal is to check auth between pages. It works randomly but if I do it rapidly. It freezes at loading.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
