### ISSUE TITLE
useQuery fetchPolicy bug

### ISSUE THREAD

**Issue by moon-stripe** [apollographql/react-apollo#3302]
**Intended outcome:**
`useQuery` with the same query called twice with `fetchPolicy: 'no-cache'` or `fetchPolicy: 'network-only'` should make two network requests.

**Actual outcome:**

Only one network request is made, and cached data is returned for the second `useQuery`.

**How to reproduce the issue:**

I modified the example in this repo:
https://github.com/sodiumjoe/react-apollo/tree/bug-repro
**Version**

➤ npx envinfo@latest --preset apollo --clipboard
```
npx: installed 1 in 1.025s

  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.15.2 - ~/.nodenv/versions/10.16.0/bin/yarn
    npm: 6.9.0 - ~/.nodenv/versions/10.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
  npmPackages:
    apollo-cache: 1.3.2 => 1.3.2
    apollo-cache-inmemory: 1.6.2 => 1.6.2
    apollo-client: 2.6.3 => 2.6.3
    apollo-link: 1.2.12 => 1.2.12
    react-apollo: file:./packages/all => 3.0.0-beta.1
```

**Comment by hwillson** [comment]
@moon-stripe this is actually by design. Apollo Client has a `queryDeduplication` feature that is enabled by default. You can read more about in the [API docs](https://www.apollographql.com/docs/react/api/apollo-client/#apolloclient), but if you adjust the `ApolloClient` instantiation like

```js
const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
  queryDeduplication: false
});
```

you'll see the extra network request.

**Comment by pacific0437** [comment]
the same problem!
![image](https://user-images.githubusercontent.com/7251055/63091836-424d3f80-bf92-11e9-8e9b-5834406e9091.png)
the query variable is the same, queryDeduplication has been set false
after equal , the code return cache result directly. I expect It run the else part when fetchpolicy is network-only

**Comment by scf4** [comment]
Same problem, I don't think this has anything to do with query deduplication

**Comment by hwillson** [comment]
@pacific0437 @scf4 The reproduction provided in https://github.com/apollographql/react-apollo/issues/3302#issue-476010962 is fixed by adding `queryDeduplication: false` to it, so it sounds like your issues are different. Would you be able to open a new issue with a small runnable reproduction? Thanks!

**Comment by scf4** [comment]
@hwillson My issue was due to `ssrMode: true` rather than `ssrMode: typeof window === 'undefined'`. My mistake!
