### ISSUE TITLE
fetchData is not being called on the server side

### ISSUE THREAD

**Issue by thomasbaldwin** [apollographql/react-apollo#3329]
**Intended outcome:**

Promises returned inside fetchData() are expected to be resolved during getDataFromTree on the server side

I'm server side rendering, and manually firing the queries from fetchData on the server side and trying to populate the redux store with the data, however, fetchData is not even being called. This worked in previous versions of react-apollo (specifically `2.1.3` )

**Actual outcome:**

Fetch data is not called, and therefore my queries aren't being fired

**How to reproduce the issue:**

Create a fetchData() method which returns a promise (or even console log) in a component, and call getDataFromTree(). Your promises will not end up being awaited / resolved. It seems fetchData in general is not being called

**Version**
react-apollo@2.5.8

**Comment by thomasbaldwin** [comment]
Can anyone confirm whether this method is still supported in the latest version of Apollo? I don't see it in the docs anywhere anynmore

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
