### ISSUE TITLE
[Hooks] Query return prev. results when vars changed

### ISSUE THREAD

**Issue by Fyzu** [apollographql/react-apollo#3332]
**Intended outcome:**

After receiving first query fetch.
When variables for query change, prop "data" contains old query results while loading.
Results are updated only after fetch is complete.

**Actual outcome:**
When variables for query change, prop "data" is undefined while loading.

**How to reproduce the issue:**
https://codesandbox.io/embed/apollo-client-error-template-bnu9n

**Version**
```
    "@apollo/react-common": "^3.0.0",
    "@apollo/react-hooks": "^3.0.0",
```

**Comment by hwillson** [comment]
@Fyzu This is by design. The previous values are maintained to help prevent potentially jarring side effects in an apps UI, when the next data set is being loaded. With the loading indicator flipping to `true` though, you can decide if you want to show or not show the previous data, using fairly app level logic.

**Comment by Fyzu** [comment]
I migrated from `react-apollo-hooks`, there behavior was different.
Thanks for answer!
