### ISSUE TITLE
useQuery: useEffect doesn't run on cache update

### ISSUE THREAD

**Issue by levrik** [apollographql/react-apollo#3357]
**Intended outcome:** After updating the cache via `cache.writeQuery` inside `update` of an mutation, I expect the updated query results to cause `useEffect` to run again if `data` is passed as dependency.

**Actual outcome:** A re-render was triggered but `useEffect` which have `data` passed as dependency doesn't run again. It seems like the reference to `data` stays the same.

**How to reproduce the issue:**

I used `useMemo` in this example but the result is the same with `useEffect`, `useCallback` and similar.

https://codesandbox.io/s/apollo-client-error-template-dj88f

Pay attention to the peoples count.

**Version**

`@apollo/react-hooks 3.0.0`

**Comment by lensbart** [comment]
Have you tried avoiding to mutate the local store data? I had a somewhat similar issue (component not rerendering although the store had been updated), and this turned out to solve my problem. You can configure your Apollo Client instance to enforce immutability, which might come with a performance benefit as well: see https://github.com/apollographql/apollo-client/pull/4543

**Comment by levrik** [comment]
@lensbart Actually I'm mutating the array but then creating a new array out of it when passing it to the `writeQuery` method. Thanks for the pointer. I'll try this option.

**Comment by pawelkleczek10c** [comment]
I've updated the example to @lensbart advice, seems working better now. Wtyt?
https://codesandbox.io/s/apollo-client-error-template-lcber

**Comment by hwillson** [comment]
It sounds like this has been resolved, so I'll close this off. Let us know if not. Thanks!
