### ISSUE TITLE
Use of GraphQL interfaces fragments causes component to always fetch data from server even if it should already be cached in redux

### ISSUE THREAD

**Issue by TSMMark** [apollographql/react-apollo#336]
Related issue: https://github.com/apollostack/apollo-client/issues/933

## Steps to Reproduce

 1. Create a component whose query includes an [interface fragment](http://graphql.org/learn/schema/#interfaces).

```graphql
const query = gql`query {
  notifications {
    id
    type
    ... on MyInterfaceType {
      field_a
      field_b
    }
  }
}`


const ComposedComponent = compose(
  graphql(query)
)(OriginalComponent)
```

 2. Mount the `ComposedComponent` and observer network traffic. You should see a network request was made to fetch the data (this is expected).
 3. Unmount the `ComposedComponent`, and remount it. You should see that an additional network request was made, even though the data should have been cached in step 2.

### Buggy Behavior

Another network request should not be made in step 3.

### Expected Behavior

Remounting the component should utilize the cached local data instead of doing an identical remote fetch.

### Version
- apollo-client@0.5.6
- react-apollo@0.6.0

**Comment by TSMMark** [comment]
@stubailo any pointers where to start looking in the source if I wanted to open a PR?

**Comment by tmeasday** [comment]
@TSMMark are you saying it doesn't happen if you don't use fragments?

I would start by tracing from this line: https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L395

and seeing what happens when it reaches https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L459

**Comment by TSMMark** [comment]
> are you saying it doesn't happen if you don't use fragments?

@tmeasday Yes, exactly. 

Thanks for those links, I will start digging into it ASAP.

**Comment by TSMMark** [comment]
When we reach [this line](https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L488),

```js
const { isMissing, result } = diffQueryAgainstStore({
        query: queryDoc,
        store: this.reduxRootSelector(this.store.getState()).data,
        returnPartialData: true,
        variables,
        config: this.reducerConfig,
      });

      // If we're in here, only fetch if we have missing fields
      needToFetch = isMissing;
```

if fragments are used in the query, `isMissing` is `true` every time. If no fragments are used in the query, `isMissing` is `true` only on the first component mount, and `false` on subsequent mounts, as expected.

**Comment by tmeasday** [comment]
Interesting. Any idea where `diffQueryAgainstStore` is going wrong? Perhaps at root this is a problem with `graphql-anywhere` or our use of it in AC.

It would be great to create a failing test case against apollo at this stage. Probably easiest would be a version of [this test](https://github.com/apollostack/apollo-client/blob/master/test/QueryManager.ts#L1108) that uses fragments, but if we are right about where the problem is, an even simpler test would be like [this one](https://github.com/apollostack/apollo-client/blob/master/test/readFromStore.ts#L66)

**Comment by helfer** [comment]
@TSMMark I think @tmeasday is spot-on here. A failing test on apollo-client or graphql-anywhere would be very helpful!

**Comment by tmeasday** [comment]
@TSMMark when you were debugging the line above, did you take a look at the `result`? Did it have missing fields? If so, which ones?

**Comment by jbaxleyiii** [comment]
I believe this is working now? We should add a test for it in RA though
