### ISSUE TITLE
Input is losing focus after re-render, with provided key when using useQuery

### ISSUE THREAD

**Issue by hsanoyan** [apollographql/react-apollo#3405]
I'm trying to implement search with `useQuery`, here is the code in [codesandbox](https://codesandbox.io/embed/new-voslv). Problem is that input is losing focus on queries first time. When keyword already used for query, input will keep the focus. Meaning if you type once 'luke' than you can clear and type 'luke' without losing focus. I'm not sure if this is issue or is this apollo  related issue, but I can't replicate it without apollo so I some recommendations from you could be nice.

**Comment by csoLs** [comment]
@hsanoyan this is not related to `react-apollo`. 
It's due to the nature of React (and your code).
When you start typing your `handleChange` will call apollos `refetch`, which in turn will make `loading` true and your function will return early and unmount the input and you'll loose focus.

The easiest fix is to make sure your function doesn't unmount the input by removing L28 (`if (loading) return "loading"`) and instead implement some loading state under the input:
```
{loading ? 'loading' : data.persons.map(c => {
  return <span style={styles.span}>{c.name}, </span>;
})}
```

**Comment by hsanoyan** [comment]
Seems clear, thanks for your time.
