### ISSUE TITLE
Wrong Types (or wrong behavior?) with onCompleted

### ISSUE THREAD

**Issue by Titozzz** [apollographql/react-apollo#3428]
**Intended outcome / reproduction:**
Types should be trustworthy but:

Using onCompleted(data), typescript says that data cannot be undefined, but onCompleted is called with undefined.

An easy way to reproduce is to do useQuery with cache-only.
Demo:
https://codesandbox.io/s/nifty-northcutt-0ukec

Either onCompleted should not be called when data is not in cache or type should warn that data can be undefined.

Type are specified as follow:
```
export interface QueryFunctionOptions<TData = any, TVariables = OperationVariables> extends BaseQueryOptions<TVariables> {
    displayName?: string;
    skip?: boolean;
    onCompleted?: (data: TData) => void;
    onError?: (error: ApolloError) => void;
}
```

**Version**

  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1
  npmPackages:
    apollo: 2.17.2 => 2.17.2
	@apollo/react-hooks: 3.0.1

**Comment by hwillson** [comment]
@Titozzz while working on a separate `onCompleted` issue, I've added a test to verify that `onCompleted` receives `data` properly when using `cache-only`. Everything appears to be working properly (with the latest soon to be published code). Can you take a look a the test in https://github.com/apollographql/react-apollo/pull/3461 to see if I'm missing anything that could cause this to happen? I'll close this for now since everything appears to be okay, but let me know otherwise. Thanks!

**Comment by Titozzz** [comment]
@hwillson The bug is still here, I've just updated my codesandbox to 3.1.3 and I still can reproduce. Maybe we should reopen this? 😄
