### ISSUE TITLE
Undocumented wait util on @apollo/react-testing

### ISSUE THREAD

**Issue by VincentVW** [apollographql/react-apollo#3685]
Posting as a discussion since I don't know if there's reasons not to document. 

The API documentation of @apollo/react-testing does not mention 
```
import { wait } from '@apollo/react-testing';
```
while it can be imported.

https://www.apollographql.com/docs/react/api/react-testing/

Also in this documentation: https://github.com/apollographql/apollo-client/blob/master/docs/source/development-testing/testing.mdx#testing-final-state

The "Testing final state" example imports a wait method from the `waait` library. While on the same page, `MockedProvider` is imported. The implementation of these 2 wait methods look exactly the same. Might be good to save people from adding the extra dependency and change that to an import from @apollo/react-testing ?

**Comment by rubencodes** [comment]
Bump. Is it safe to rely on this?

**Comment by hwillson** [comment]
@rubencodes No, it's not safe to rely on it. `@apollo/react-testing` is being merged into the Apollo Client project, and will be available as `@apollo/client/testing` when Apollo Client 3 launches. AC3 does not include the `wait` util. We're not including it as we don't use it internally, and because the functionality it offers is super simple to re-create when needed:

```ts
export function wait(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```
