### ISSUE TITLE
Refetch after server 500 error not updating loading state

### ISSUE THREAD

**Issue by msmfsd** [apollographql/react-apollo#430]
## Steps to Reproduce
1. Load app and have a form that on submit renders a graphql component with forceFetch set to true that fetches the data with the forms variable/s
2. turn off backend api and click submit
2. The component shows loading correctly and after server timeout it errors correctly
4. The graphql component on error shows a button to retry
3. On click of retry button it triggers graphql `refetch` method `onClick={props.data.refetch}`

### Buggy Behavior
On refetch the loading state is not updated to true. It does error again after the server times out again but data.loading is not updated.

### Version
- react-apollo 0.8.0
- apollo-client 0.8.3

### error
![screen shot 2017-01-24 at 10 08 56 am](https://cloud.githubusercontent.com/assets/17868999/22227049/455f4830-e21d-11e6-9ed5-a1e7fc9aa9dc.png)

**Comment by msmfsd** [comment]
NOTE: this issue does not happen if I clear the form and graphql component so that `APOLLO_QUERY_STOP` fires.

**Comment by msmfsd** [comment]
Bump for this issue - would be great to have props for refetch loading and also mutate loading/error - https://github.com/apollographql/react-apollo/issues/421

**Comment by calebmer** [comment]
`onClick={props.data.refetch}` is going to give you some trouble because an `event` object is going to get passed into `refetch` 😣. `onClick={() => props.data.refetch()}` is going to be better. I don’t think that’s the issue here, but it may be why you have a “circular structure to JSON error.”

Second, what version of Apollo Client are you on, and does this work on `0.7.3`? We did a refactor in `0.8.0` of loading state, so there may be a regression. You said you were on version `0.8.3` of `apollo-client`, but I’m not sure how given we are currently on version [`0.8.1`](https://github.com/apollographql/apollo-client/blob/fb950743f993b03a60b1264582125b3b8ca6110e/CHANGELOG.md).

**Comment by msmfsd** [comment]
Thanks @calebmer 

I am on apollo-client 0.8.0. I am using state workaround and my refetch now looks like this:
```
onClick={this.refetch}

refetch = (): void => {
    const { refetch } = this.props
    this.setState({ refetching: true })
    refetch()
      .then(() => {
        this.setState({ refetching: false })
      })
      .catch(() => {
        this.setState({ refetching: false })
      })
  }
```

**Comment by calebmer** [comment]
Interesting, could you put together a small reproduction?

**Comment by msmfsd** [comment]
This is fixed, see: https://github.com/apollographql/react-apollo/issues/584#issuecomment-291665248
