### ISSUE TITLE
queryObservable errors are not thrown

### ISSUE THREAD

**Issue by SachaG** [apollographql/react-apollo#433]
I've stumbled onto a small hack that's really been helping me debugging my reducers lately, and I thought it might be a good idea to make it standard. Basically, errors in [`queryObservable`](https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L465) are not surfaced to the client. 

I've added the following code in my own copy of the `react-apollo` package at around line 485, and it's been a big help:

```js
if (this.queryObservable.lastError) {
  console.log(this.queryObservable.lastError)
}
```

An example of the kind of errors I now see (and as far as I know, there's no way to access them currently):

```
Error: Network error: Can't find field parent on object (CategoryRkFPwKk7twWsjCviW) {
  "_id": "RkFPwKk7twWsjCviW",
  "name": "cat 8",
  "description": null,
  "order": null,
  "slug": "cat-8",
  "image": null,
  "parentId": null,
  "__typename": "Category"
}.
Perhaps you want to use the `returnPartialData` option?
```

**Comment by tmeasday** [comment]
Isn't the error passed into the component as `data.error`?

**Comment by SachaG** [comment]
Not as far as I can tell. Even so, I think it'd be best to throw an error or warning in the actual console?

**Comment by tmeasday** [comment]
What if the user wants to handle it?

**Comment by SachaG** [comment]
But how would the user even know about the error in the first place if it's not shown anywhere?

**Comment by tmeasday** [comment]
I mean your wrapped component should look at the `error` property, just like it looks at the `loading` property.

**Comment by SachaG** [comment]
It feels weird to ask the user to implement part of their error reporting infrastructure in their own UI, honestly. 

If someone doesn't know they're supposed to do this (as was my case), they'll be missing out on important errors and probably end up spending a lot of time hunting for a solution. So I don't really understand the rationale for not surfacing these errors in the console as well?

**Comment by tmeasday** [comment]
Errors can happen for legit reasons beyond you making a mistake in code though; like the server could be down, or do something weird or whatever. So production code (a) probably needs to do something sensible in such cases, and (b) probably doesn't want to show the error in the browser console if doing (a). 

It might make sense to add a `debugErrors()` export to `react-apollo` that people can call to get the logging behaviour you want though?

**Comment by abhiaiyer91** [comment]
I agree that production code should probably not expose these to the console, but having a hook into error reporting in development sounds awesome.

If you guys have a spec, I'd love to contribute.

What I've been doing, through composition, is rendering client errors through a HOC, but it really isnt ideal and kinda awkward to do that type of error reporting at the UI level.

Another thing about having a hook into errors means you can use a 3rd party service to capture those errors, e.g. Sentry

**Comment by SachaG** [comment]
Maybe the Apollo Devtools could plug into that hook, too?

Also, just to reiterate the error I've been running into is *not* passed on to the container's `props` callback. `props.data.error` is just `undefined`.

**Comment by tmeasday** [comment]
@abhiaiyer91 perhaps let's open a separate issue about a global `onError` hook / a default on in development. I'm not sure if it's more appropriate to attach that to the AC `Client` instance, or make it globally exported by RA.

> Maybe the Apollo Devtools could plug into that hook, too?

This seems like a good idea.

> Also, just to reiterate the error I've been running into is not passed on to the container's props callback. props.data.error is just undefined.

Ok, let's focus on that in this issue, because as described that's clearly a bug. @SachaG do you have a reproduction of the issue?

**Comment by tmeasday** [comment]
@SachaG you are saying that `lastError` is set, but that `currentResult` doesn't include `error` on [this line](https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L475)? If so that sounds a lot like a bug in AC, but a repro would be good.

**Comment by brunoreis** [comment]
I had the same problem here and it took me around two days to debug it. Hard time for a novice. I was even thinking about throwing the towel on Apollo. What happened:

I run a migration and the props changed by it are set as undefined.  I was thinking the migration result was wrong but inspecting the http result and the store, data was sent and set correctly. 

After a long time trying to see what went wrong with the migration I discovered that what was really wrong was the value set by a graphql query. It seems obvious now to me that the injection is the query's responsibility, but it was not so straightforward for a novice. 

Unfortunately the query was injecting an undefined prop and no error message was injected on the component. Component gets only error:undefined. ObservableQuery does have a lastError, but it's not passed down to the component. It seems that it could happens somewhere inside dataForChild, but the _observableQueryFields_ does not include lastError and _dataForChild_ does not either. @tmeasday and @SachaG, I checked and currentResult does not include error in that place @tmeasday  indicated. 

So the error was: "Error: Network error: Can't find field canHaveItems on object (Subtopic187) { "id": "187", "name": "test", "subtopics": [], "__typename": "Subtopic" }. Perhaps you want to use the `returnPartialData` option? at new ApolloError". And then I was able to change the query returned by the mutation and fix it very easily. If the message was available easier, I could have done it at the very first moment. 

I was just a little confused by the title: "Network error" since the query was being issued against the store, but it was fast to understand.

IDEAS

Since the query data prop field _error_ on docs is described like this: 

````
error: An ApolloError object that represents the different possible errors that might happen when running a query.
```

It makes a lot of sense that the error should be added there. 

@tmeasday, I'm very new to all this libs, are you sure the error should be coming on currentResult?  Because, it could be grabbed also from _queryObservable_ inside _dataForChild_ and injected into the error prop. For sure it would have saved my day. 

Now, talking about the specific error I received, I also suggest that this requirement could be more emphasised on the docs. It was not clear to me that I needed to return all the fields (non partial data) on the mutation query. It might be deducted from the understanding of the server 
internals, but for sure some redundancy is welcome for those novice like me trying to understand all this stuff for the first time.

**Comment by brunoreis** [comment]
BTW, I was not able to debug the AC well. I changed files but they did not seem to be compiled by webpack. It was more like they were pre-compiled in a big js files. If you have any hints on how to debug AC, please help me on that.

**Comment by tmeasday** [comment]
> are you sure the error should be coming on currentResult?

`currentResult` is supposed to return the error if the query is in an error state. `lastError` is a newer thing and should probably be consistent with that I would have thought. 

Is the reproduction in your case the server query returning `null` for a field? Are you doing a query with `noFetch`?

**Comment by brunoreis** [comment]
It's returning undefined. No, I don't set _noFetch_ or anything like that. Unless it's a default option. 

This is the query: 

```
const SUBTOPICS_QUERY = gql`
    query{ 
      subtopics(root:true) {
        id
        name,
        canHaveItems,
        subtopics{
          id,
          name,
          canHaveItems,
          subtopics{
            id,
            name,
            canHaveItems,
            subtopics{
              id,
              name
              subtopics{
                id,
                name
              }
            }
          }
        }
      }
    }
`;
```

This is the mutation: 

```
const SUBTOPIC_REGISTER_MUTATION = gql`
    mutation subtopicsRegister($parent_id: ID!,$name: String!){
    	subtopicsRegister(parent_id:$parent_id,name:$name) {
            id,
            name,
            subtopics{
                id,
                name,
                subtopics{
                    id,
                    name,
                    subtopics{
                        id,
                        name,
                        subtopics{
                            id,
                            name
                        }
                    }
                }
            }
        }
    }
`;
```

And the error is the one I have put here before: 

```
Error: Network error: Can't find field canHaveItems on object (Subtopic187) { "id": "187", "name": "test", "subtopics": [], "__typename": "Subtopic" }.
```

It makes sense to me that the error should happens, since _readFromStore_ have checks for partial data. The deal here is that I don't have access to the error.

**Comment by brunoreis** [comment]
To reproduce it, I think you don't need any complicated structure. Just have a query with an object with 4 fields and a mutation that update that object (with the same id), but return less (1,2 or 3) fields.

**Comment by brunoreis** [comment]
@SachaG, please, in which file do you put that hack?

**Comment by brunoreis** [comment]
@tmeasday, I tried to put SachaG's hack on GraphQL.prototype.render and noticed that the _lastError_ prop is not set when the code executes.

```
                /**** **** DEBUG HACK **** ****/
                if(this.queryObservable) {
                    console.log('this.queryObservable',this.queryObservable);
                    console.log('this.queryObservable',this.queryObservable.lastError);
                    if(this.queryObservable.lastError) {
                        console.error(this.queryObservable.lastError)
                    }
                }
                /**** **** DEBUG HACK **** ****/
```

But, if I inspects _queryObservable_ on the console, I can see the value. That makes me guess that the problem might be something related to a promise or asynchronous result being set late. 

The same code works and prints the error to the console if I repeat the operation.

**Comment by brunoreis** [comment]
Another information, this hack is catching that error too:
https://github.com/apollostack/react-apollo/issues/286

So, handleError is being called, but the error passed does not fulfil this check:
```
if (error.hasOwnProperty('graphQLErrors'))
```

**Comment by SachaG** [comment]
@brunoreis I was adding it in this file after this line: https://github.com/apollographql/react-apollo/blob/master/src/graphql.tsx#L465

**Comment by SachaG** [comment]
I'm revisiting this because I ran into another error, and this time it's getting properly passed to the container's props.

But while I can see this message as a return value for the /graphql query in my network tab:

```
{"errors":[{"message":"Cannot query field \"foo\" on type \"Post\".","locations":[{"line":18,"column":3}]}]}
```

The corresponding error message only says this:

```
Error: Network error: Network request failed with status 400 - "Bad Request"
```

Is that expected? Could we augment Apollo's error message with the extra information returned by the request?

**Comment by calebmer** [comment]
@SachaG that’s interesting. We recently made a change in https://github.com/apollographql/apollo-client/pull/1205 so that if a request is not ok ([`!request.ok`](https://github.com/apollographql/apollo-client/blob/fb950743f993b03a60b1264582125b3b8ca6110e/src/transport/networkInterface.ts#L189)) then we throw an HTTP related error. So this means you either need to return 200 from your server for validation errors (it would seem it returns 400 now), or we need to check if there is a JSON body with errors before throwing a network error in the network interface. We should definitely look into providing a better error message in this case that looks something like Relay’s error messages when this happens. In this case we do [attach the response](https://github.com/apollographql/apollo-client/blob/fb950743f993b03a60b1264582125b3b8ca6110e/src/transport/networkInterface.ts#L191) to the error if you want to handle the error with some custom logic.

**Comment by SachaG** [comment]
Oh thanks. I found the response on `data.error.networkError.response` but even then it's not obvious to me how to access the actual details of the error. The `body` is a `ReadableStream` and I'm not sure what to do with it…

**Comment by calebmer** [comment]
You should be able to call `response.json()` or `response.text()` which both return promises 👍

The `response` object is what gets returned from `fetch`: https://developer.mozilla.org/en-US/docs/Web/API/Response

**Comment by SachaG** [comment]
Oh thanks, that makes sense. It seems like you need to add quite a bit of extra logic to display the result of a promise in a React component though, so I'll probably wait until this is standardized a bit more inside `react-apollo` itself.

**Comment by jbaxleyiii** [comment]
@SachaG do you still have thoughts / needs around better error handling in RA? I think it is still a point for improvement! If so, feel free to open this back up or start an error specific issue for discussion
