### ISSUE TITLE
Subscription HOC

### ISSUE THREAD

**Issue by abhiaiyer91** [apollographql/react-apollo#455]
I'd like to separate the subscription concerns away from the main GraphQL container. I'd like to build an HOC to manage Subscriptions independently.

Is this a bad idea?

**Comment by helfer** [comment]
@abhiaiyer91 I don't think it's necessarily a bad idea, but I think we might be moving in the opposite direction where every graphql operation is an observable. However, that's motivated by the graphql perspective and might not be the best idea for certain scenarios, so I'm curious to know what your use-cases are and what things would be improved by having a separate subscription HOC!

**Comment by abhiaiyer91** [comment]
I tend to be in the camp of single responsibility tools. I think isolating all the subscription logic into its own higher order component would be easier to digest/grok.

But if the module as a whole is going in a different direction, then I'd rather go with the flow.

**Comment by JBradBarnes** [comment]
I agree that an HOC would be nice, the flow of Redux and Apollo HOCs would fit well with it, but I haven't gotten into subscriptions enough to know whether or not it would be advantageous.

**Comment by jbaxleyiii** [comment]
@abhiaiyer91 what do you want out of a subscription HOC?

**Comment by abhiaiyer91** [comment]
@jbaxleyiii let's close this issue. I've since changed my opinions, I'm all down with the single container

**Comment by JBradBarnes** [comment]
@jbaxleyiii   I know I'm late on the reply here, but I still think there would be value in a subscribe HOC.

I don't know if I can speak for everyone here, but in my limited experience setting up subscriptions (in React at least) was messy. It required the React component life cycle instead of using stateless components, and I found myself repeating the same awkward process.

I ended up just creating my own HOC to keep code from inflating on me in multiple files.
Here's what I did:

```
//Subscriber.js
import React, { Component, PropTypes } from 'react'

const Subscriber = (document, config) => {  
  return (WrappedComponent) => { 

    return class extends Component {

      constructor(props) {
        super(props)
        this.subscription = null
      }
        componentWillReceiveProps(nextProps) {
          if (!this.subscription && !nextProps.data.loading) {
            let { subscribeToMore } = this.props.data
            this.subscription = [subscribeToMore(
            {
              document: document,
              variables: config.variables(this.props),
              updateQuery: (previousResult, { subscriptionData }) => {
                var newResult = [subscriptionData.data[config.modelName].node].concat(previousResult[config.propName])
                return { 
                  [config.propName]: newResult,
                }

              },
              onError: (err) => console.error(err),
            }
              )]
              }
            }


      render () {

        if (this.props.data.loading) {
          return (<div>Loading</div>)
        }
           return (
                  <WrappedComponent {...this.props} />
                 )
        
      }
    }
  }
}

export default Subscriber

```
Then I would call it with the standard graphQl HOC for the query

```
export const ComponentList = graphql(<query document>, 
   {options: (ownProps)=>({
     variables: {
       <query variables>
     }})})(Subscriber(<subscription document>,{
        //need propName and modelName because I didn't want to parse the subcription document
       //so this is just my returned data property names
        propName: "allComponents",
        modelName: "Component",
        variables: (ownProps)=>( 
          {
           <subscription variables>
          } 
        ),
      })(<ListComponent>))
```
This kept the trash out of my components. I know its not a end-all use case. But it was hard to get subscriptions to work, and even harder to keep my components clean. I know that there is an easier, more intuitive way to handle subscriptions somehow with the power of HOCs and maybe Redux that will help someone at my beginners level keep moving in Apollo instead of getting stuck on subscriptions for 
 a day or more.

But I could be missing something here. I do still have a lot to learn.  
@abhiaiyer91 I would love to learn what changed your mind on this particular subject.

Thanks

**Comment by s-chand** [comment]
An HOC pattern would really be cleaner
