### ISSUE TITLE
Remove __typename property from query result [Request]

### ISSUE THREAD

**Issue by sun2rise** [apollographql/react-apollo#463]
When i make a query the object that i got back includes the `__typename` property... is there a way to have a "clean" object with the requested properties only?

The way that it is now if i want to modify that object and mutate it back as update i got errors because it doesn't reflect the model anymore.

**Comment by calebmer** [comment]
You can clone the object and omit `__typename` with a function like `omit` from Lodash or with ES6.

Omit:

```graphql
const cleanObject = omit(object, ['__typename']);
```

ES6

```graphql
const { __typename, ...cleanObject } = object;
```

We probably won’t add this feature because it is easy to do in userland, so I’m going to close. If you disagree, please let us know. Why do you want a clean object without `__typename`?

**Comment by sun2rise** [comment]
**I disagree you Honour because:**
if you have nested arrays of objects the use of omit (which i tried to use just before posting the issue) won't work on every element and sub-element of the array because you will get this error:
`Uncaught TypeError: Cannot assign to read only property`

consider this:
```
company {
  registry {
    name
  }
  addresses [{
    street
    contacts [{
      name
      phone
    }]
  }]
}
```
inside an object called `variables`

if you have `__typename` inside the contact _.omit won't work ... `Uncaught TypeError: Cannot assign to read only property`

```js
variables = _.omit(variables, '__typename');
    variables.registry = _.omit(variables.registry, '__typename');
    variables.addresses = variables.addresses.map((a) => {
      a.contacts = a.contacts.map((c) => {
        return _.omit(c, '__typename');
      });
      return _.omit(a, '__typename');
    });
```

so it's ok to keep `__typename` but at least it should be not read only, or i have missed something :)

Anyway with that property you disrupt the beauty of querying an object, modify it and mutate it back without any fuss.
By the way, i honestly don't know what is the purpose of `__typename` property, where can i read more about it?
Thanks!

**Comment by calebmer** [comment]
`__typename` allows us to know the type of the object we are querying from the API. There are a number of places where we need that information throughout Apollo Client 😊

The reason you are getting an error is not because of `omit`, but rather because of your assignments: `variables.registry =`, `variables.addresses =`, etc. So if we made `__typename` read only it wouldn’t matter.

If you _really_ want to omit `__typename` this will work:

```js
function omitTypename (value) {
  if (value !== null && typeof value === 'object') {
    const nextValue = {};
    Object.keys(value).forEach(key => {
      if (key !== '__typename') {
        nextValue[key] = omitTypename(value[key]);
      }
    });
    return nextValue;
  } else if (Array.isArray(value)) {
    return value.map(item => omitTypename(item));
  } else {
    return value;
  }
}
```

**Comment by sun2rise** [comment]
yeah, my final workaround is something very very similar :)
ok, thank you, now i know i cannot make it better because it's already ok!

**Comment by jacobk** [comment]
@calebmer if you don't mind me asking... but since you are active on flow type now, do you have any suggestion on how to type the suggested `omitTypename` above? https://github.com/apollographql/react-apollo/issues/463#issuecomment-280174867
