### ISSUE TITLE
Feature Request: Reselect Support

### ISSUE THREAD

**Issue by fabriciovergal** [apollographql/react-apollo#475]
I have an application with 4 animated tabs, each tab contain a list which shows about 10 to 1000 items, when I try do switch between tabs the react-apollo container load data from redux store really fast, but not enough to prevent a little freeze in the tab switch animation. 

There is some way to prevent this kind of behavior or add reselect in the react-apollo container ? 
 
## Steps to Reproduce

Create app with tabs and load a list with 100 items from redux store using react-apollo container.
To prevent this behavior I'm currently using static container, keeping all tabs rendered and  hiding the non-selected tabs.

```javascript
  const renderTab = (item, isSelected) => (
    <View
      key={item}
      paddingHorizontal={8}
      position={'absolute'} top={0} left={0} bottom={0} right={0}
      opacity={isSelected ? 1 : 0}
      removeClippedSubviews={!isSelected}
      pointerEvents={isSelected ? 'auto' : 'none'}>
      <StaticContainer shouldUpdate={isSelected}>
        {isSelected && <OverviewContent type={item}/>}
      </StaticContainer>
    </View>
  );
```

### Buggy Behavior

Little freeze in the UI.

### Expected Behavior

Load the tab without any freeze

### Version
"apollo-client": "0.8.7",
"graphql-tag": "1.2.4",
"react-apollo": "0.11.1",

**Comment by calebmer** [comment]
Your approach using `StaticContainer` is probably best at the moment. We do use something like reselect internally, the problem is it just isn’t as fast as it could be. We should really work to optimize reading from the store, and if that isn’t enough we should cache denormalized query results as well if that will be significant for a large number of people.

We are currently working on some store refactors so hopefully this will get faster soon.

**Comment by csillag** [comment]
> we should cache denormalized query results as well if that will be significant for a large number of people.

:+1: 

> We are currently working on some store refactors so hopefully this will get faster soon.

Do you have any idea when that might come to fruition?

**Comment by SebastianSchenk** [comment]
Any updates?
