### ISSUE TITLE
Added keys in updateQuery aren't available in component props

### ISSUE THREAD

**Issue by NiallBrickell** [apollographql/react-apollo#487]
When an item is added either directly on the returned object from updateQuery, or on a nested child object, the added items aren't reflected in the wrapped component props. 

Example repo here: https://github.com/NiallBrickell/react-apollo-error-example

**Comment by calebmer** [comment]
This is expected because `test2` is not included in your GraphQL query. When we read from the cache we are only reading the fields you specified in your query and nothing else. In fact the fields you add will never be written to the cache because we use the same query heuristic to know which fields to write. We are considering adding client fields which could support adding a `test2` field to your GraphQL query without it being in the GraphQL server schema, but it would be good to know your specific use case.
