### ISSUE TITLE
Help needed about complex updateQueries (or complex query reducers)

### ISSUE THREAD

**Issue by cyrilepinat** [apollographql/react-apollo#620]
Hi !
I have a question if any of you can give me your feedbacks, it would be awesome. If this is not the good place to ask, don't hesitate to remove this issue.

Our app is becoming very fat and we're now facing problems with data in store and updateQueries.
We are displaying many pages with many list that are using filters, parent id, search pattern... so many reason that they can become inconsistent after some mutations, because we need to take in account a lot of variables (and so a lot of different cases) retrieved from many different locations... 

So my question is: Are you working on big complex app ? And if yes how you guys are you handling your updateQueries, or query reducers (or something else) to handle every cases. What is your way to do to make it as most generic and reusable as you can and be able to take in account variables in updateQueries to know if each query must be updated or not ? Or do you use a fetchPolicy 'network-only' with a cache on your server side ? or something completely different ? 

Thks for your feedbacks

**Comment by helfer** [comment]
Hi @cyrilepinat! Usually I would recommend that people ask this kind of question in the slack channel, but I think this is a case that will soon be common enough that it's worth talking about it here in order to keep a record for others who are interested in the same question.

To kick-start the discussion, I think it would be great if you could provide some examples of views (just the high-level) that you have, and when and how you are updating them.

It's also worth noting that we recommend that people use the new `update` API to make store updates instead of relying on `updateQueries` or `reducer`. However, with `update` you have to keep track of the variables yourself, so it could be quite tricky.

We're also working on redesigning the API of apollo-client and react-apollo a bit. It would be very helpful to have a good description of your use-case somewhere, so we can take it into account. We'd also love to get your feedback on the new design once we put it out there.

Thanks! 🙂

**Comment by jbaxleyiii** [comment]
@cyrilepinat do you have any more feedback on this?

**Comment by cyrilepinat** [comment]
Yes @helfer @jbaxleyiii I'm really sorry I ask questions and don't have enough time to provide you details about it. That's quite useless sorry. 
After some research, I think refetchQueries is what I need for complex cases, and I follow issue #622 too that provides good answers to my question I guess. So for now, I think I'm good. Thanks for your time.

**Comment by AdamYee** [comment]
Hi guys and gals. As you say @helfer, the docs now indicate that using a query `reducer` isn't recommended and instead use `update`. It also says,

>The reason we are considering deprecating reducer and updateQueries is that they both depend on state internal to the client, which makes them harder to understand and maintain than update, without providing any extra functionality.

I would argue that `update` isn't that much more flexible than `reducer` aside from having the ability to update any part of the store with `update`. The `reducer` is a nice way to update the cache (for a specific query) after a mutation in just _one_ place. I've got multiple places where I perform the same mutation (multiple ways to create something), which means that I'll need to perform the same `update` in all those places. It seems to me that the `reducer` does provide extra functionality by scaling with multiple mutations of the same `operationName`.

Perhaps this is something to consider as you guys are redesigning the API. Thoughts?

**Comment by helfer** [comment]
@AdamYee you're right that there are cases where using `reducer` is more convenient. The main reason I'm no longer a fan of using it is that it requires keeping around instances of queries even when the components that asked for it have been unmounted, because otherwise those parts of the store won't be up to date any more when the component remounts. It's not clear how long to keep things around, or whether that should be a complexity that the client offloads to the user.
`update` doesn't have that problem, because it works with query documents instead of references to query names.

**Comment by AdamYee** [comment]
Hi @helfer. A lot of that went over my head because I don't know the internals of the client, but I think I understand the gist. If I wanted to understand in better detail, could you recommend some places to start learning? I appreciate you taking the time to get back to me. Really enjoying working with react-apollo and I hope to continue down a path of contributing to it. I think this issue is now resolved?

**Comment by cyrilepinat** [comment]
Hi @helfer, I'm trying to migrate my `updateQueries` to `update` or `refetchQueries` (with real query instead of string query name) and for most of my cases, I cannot know the exact set of variables to pass to `readQuery`, so it's very difficult to use and so much complex - maybe even not possible - to create generic methods for reusability.
I'm wondering if it is possible (or will be in the future) to have a kind of  `findQueries` method in store proxy object that allows to fetch the store and find the instances of queries I want to update or not (with all different set of variables). It's maybe very close to how is working `reducer` or `updateQueries` right now but I don't see how I can update my queries with `update/refetchQueries` without handling like a mirror of apollo store to have access to all my set of variables. It seems very overkilling isn't it ? Maybe I'm missing something, so would be nice to have your feedback on this.
Thanks for your help.
