### ISSUE TITLE
CSRF issues due to use of POST queries

### ISSUE THREAD

**Issue by camd** [apollographql/react-apollo#624]
I have an application where the ReactJS app is hosted on one domain, and the Django service (using Graphene) is hosted on another.  The ReactJS app needs to access the data in the Django app.

## Steps to Reproduce

Since Apollo defaults to using POST for queries, I'm hitting a CSRF issue when trying to access the data.  At this time, since these APIs are all read-only, I'm using ``csrf_exempt`` on the ``GraphQLView`` and this is working OK.

However, I would much prefer to use ``GET`` for my read requests.

After some digging, I found that I could modify the method to GET by using ``applyMiddleware`` and modifying ``req.options.method = "GET"``.  However, It is still trying to post a BODY, which is not allowed in a GET.  I tried doing ``delete req.request.query`` but that didn't seem to help.  I didn't really expect that second part to work, but gave it a shot anyway...  :)

### Expected Behavior

Would you be able to either provide an additional ``NetworkInterface`` that uses GET or some documentation on how to create our own?

### Version
- apollo-client@1.0.2
- react-apollo@1.0.1

**Comment by helfer** [comment]
Hi @camd, I think a GET Network Interface would be a great thing to be implemented by someone in the community - maybe you? 🙂 You could start by copying the HTTPNetworkInterface that's currently in Apollo Client and modify it such that it sends a GET request, which means you'd have to serialize the arguments (query, variables, operationName) into the URI instead of putting them in the body. You should also make sure that any mutations are sent over POST (or an error is thrown).

I'd also be happy to accept a PR that lets people configure the current NetworkInterface to use GET for queries if a `useGetForQueries: true` is passed to it (or something like that).

This is technically an Apollo Client issue, so I'll close it here, but I hope you will open a PR on Apollo Client to continue the discussion! 👍
