### ISSUE TITLE
update on subscribeToMore (Direct Cache Access)

### ISSUE THREAD

**Issue by mitjade** [apollographql/react-apollo#634]
I would like to replace `updateQueries` with `update` (Apollo Client’s new imperative store API), but it seems `update` is currently only available on `mutations`.

### Expected Behaviour
You should be also able to use `update` on `subscribeToMore`, like you are able to on mutations

### Version
- apollo-client@1.0.3
- react-apollo@1.0.2

**Comment by helfer** [comment]
Hi @mitjade, I think you're right! Would you mind making a PR to apollo-client to fix this? I can give you some pointers to get you started, if necessary.

I'll close the issue here, since it's an apollo-client issue, but if you don't have time to make a PR, please file the same issue on apollo-client. Thanks! 🙂
