### ISSUE TITLE
Getting the status of a query from from outside the connected component

### ISSUE THREAD

**Issue by c10b10** [apollographql/react-apollo#697]
Say I have a `Search` form component that when submitted sets a part of a state. 

When the search state is changed, another `List` component that lists some data pulled with a GraphQL query updates its query to include search filtering. 

Is there any way to access the `networkStatus` of that query from outside the `List` component, say through a selector in the connected `Search` component? (I'd like to make it so the search box reflects the fact that the search is loading).

**Comment by thebigredgeek** [comment]
@c10b10 generally this is something I try to avoid.  However, when cases arise where I need to observe a child from a parent, I usually build some sort of `subscribe` prop into the child that takes a function and is passed either the state as it changes or an observable depending on the case.  That way the parent can `subscribe` to the child's state

**Comment by c10b10** [comment]
I understand why trying to access a prop in a child from a parent is not recommended. Since this is the only solution you can think of, I'm guessing there's no way to access the "networkStatus" part of the Redux state through an Apollo selector (which would be the proper way of doing it).

I guess I'm only left to moving the query on a Container component, and to pass that status down the prop chain to the List and Search components.

**Comment by thebigredgeek** [comment]
The trick here is that `networkStatus` is specific to the query.  Could you "subscribe" to the child through a passed function via a prop?  That way you can keep the query in the child but react to state within the parent.

**Comment by akomm** [comment]
A query is not something "bound" 1:1 to a component. It is even possible, that you have a query 3 times in your store with different variables, each with its own cache entry. This can be because different components use the query with different variables, or one component used the query with different variables over time and generated each time a new query entry in the store (results of all queries are normalized and therefore deduplicated).

But to answer the question:

As far as I know there are no (exposed) selectors in apollo-client/react-apollo. But assuming you moved apollo state into your own store under default property `apollo`, you can make your own selector.

The queries can be found under `state.apollo.queries`. This includes their network status. Using react-redux you can then connect the data to your search component.

You should consider that selecting vendor state with selection logic implemented in your app is risky, as vendor selectors would be adjusted to prevent BC breaks if possible, in your app's code they don't. Sadly there are no selectors provided or I missed them.
