### ISSUE TITLE
GraphQL error when not passing value for optional variables

### ISSUE THREAD

**Issue by MichaelDeBoey** [apollographql/react-apollo#707]
As you can see in Youshido/GraphQL#144, we ran into some problems when updating our backend.

If this is not possible by the GraphQL-spec (like @viniychuk said in [his comment](https://github.com/Youshido/GraphQL/issues/144#issuecomment-300812767)), shouldn't it be better to block this (and maybe throw an error) and not send a request at all to the server?

CC: @helfer

**Comment by stubailo** [comment]
We are intentionally not validating everything before sending to the server, because the server is going to check it anyway. That would just make this library heavier and more complex, or even worse inconsistent with your server behavior. Is there some reason you don't want your server to receive this request?

**Comment by MichaelDeBoey** [comment]
Not really a specific reason, but I thought you guys were validating it on the frontend also

**Comment by helfer** [comment]
@MichaelDeBoey @stubailo is right, we let the server return those errors because it makes the client a lot simpler and faster. Maybe in the future we could let people optionally do some validation in the client and not send queries that won't pass validation, but for now I think we can close this issue.
