### ISSUE TITLE
Undocumented change

### ISSUE THREAD

**Issue by asafigan** [apollographql/react-apollo#990]
I see that a new version off react-apollo was released to npm but I don't see the changes in the changelog.

The undocumented version is 1.4.14

**Comment by jbreckel** [comment]
also this new version seems to have all exports on the top level instead of `lib`

**Comment by lostpebble** [comment]
@jbreckel yep... Just starting out with React Apollo today and for the life of me couldn't figure out why importing `react-apollo/graphql` was causing an error. Turns out whatever is there hasn't been transpiled to ES5 correctly and I was getting `import` syntax errors.

Using the import at the top level solved my issue.

I'm using Typescript, not sure if that matters.
